### Logistic Regression

In [2]:
!pip install pandas numpy matplotlib seaborn scikit-learn

Collecting pandas
  Using cached pandas-2.3.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy in c:\users\786\desktop\sessions\machinelearning---deeplearning\02-logistic-regression\.venv\lib\site-packages (2.3.5)
Collecting matplotlib
  Using cached matplotlib-3.10.8-cp313-cp313-win_amd64.whl.metadata (52 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\786\desktop\sessions\machinelearning---deeplearning\02-logistic-regression\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\786\desktop\sessions\machinelearning---deeplearning\02-logistic-regression\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\786\desktop\sessions\machinelearning---deeplearning\02-logistic-regression\.venv\lib\site-packages (from pandas) (2025.3)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Requirement already satisfied: cycler>=0.10 in c:\users\786\desktop\sessions\machinelearning---deeplearning\02-logistic-regression\.venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\786\desktop\sessions\machinelearning---deeplearning\02-logistic-regression\.venv\lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\786\desktop\sessions\machinelearning---deeplearning\02-logistic-regression\.venv\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\786\desktop\sessions\machinelearning---deeplearning\02-logistic-regression\.venv\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\786\desktop\sessions\machinelearning---deeplearning\02-logistic-regression\.venv\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\786\desktop\sessions\machinelearning---deeplearning\02-logistic-regression\.venv\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: scipy>=1.10.0 in c:\users\786\desktop\sessions\machinelearning---deeplearning\02-logistic-regression\.venv\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in c:\users\786\desktop\sessions\machinelearning---deeplearning\02-logistic-regression\.venv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\786\desktop\sessions\machinelearning---deeplearning\02-logistic-regression\.venv\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\786\desktop\sessions\machinelearning---deeplearning\02-logistic-regression\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.3.3-cp313-cp313-win_amd64.whl (11.0 MB)
Using cached matplotlib-3.10.8-cp313-cp313-win_amd64.whl (8.1 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached scikit_learn-1.8.0-cp313-cp313-win_amd64.whl (8.0 MB)
Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Installing collected packages: contourpy, scikit-learn, pandas, matplotlib, seaborn

   ---------------------------------------- 0/5 [contourpy]
   ---------------------------------------- 0/5 [contourpy]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\Users\\786\\Desktop\\Sessions\\MachineLearning---DeepLearning\\02-Logistic-Regression\\.venv\\Lib\\site-packages\\pandas\\tests\\arrays\\categorical\\test_constructors.py'
Check the permissions.

In [3]:
import pandas as pd

In [5]:
df= pd.read_csv("Iris.csv")

In [14]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [7]:
# Label encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Species'] = le.fit_transform(df['Species'])
df.head()

Collecting pandas
  Using cached pandas-2.3.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Using cached numpy-2.3.5-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting matplotlib
  Using cached matplotlib-3.10.8-cp313-cp313-win_amd64.whl.metadata (52 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\786\desktop\sessions\machinelearning---deeplearning\02-logistic-regression\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.61.1-cp313-cp313-win_amd64.whl.metadata (116 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.4.9-cp313-cp313-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\786\desktop\sessions\machinelearning---deeplearning\02-logistic-regression\.venv\lib\site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Using cached pillow-12.0.0-cp313-cp313-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.2.5-py3-none-any.whl.metadata (5.0 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.16.3-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in c:\users\786\desktop\sessions\machinelearning---deeplearning\02-logistic-regression\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.3.3-cp313-cp313-win_amd64.whl (11.0 MB)
Using cached numpy-2.3.5-cp313-cp313-win_amd64.whl (12.8 MB)
Using cached matplotlib-3.10.8-cp313-cp313-win_amd64.whl (8.1 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.0 MB 2.9 MB/s eta 0:00:03
   ----- ---------------------------------- 1.0/8.0 MB 2.4 MB/s eta 0:00:03
   ------- -------------------------------- 1.6/8.0 MB 2.3 MB/s eta 0:00:03
   --------- ------------------------------ 1.8/8.0 MB 2.0 MB/s eta 0:00:04
   ---------- ----------------------------- 2.1/8.0 MB 1.9 MB/s eta 0:00:04
   ----------- ---------------------------- 2.4/8.0 MB 1.7 MB/s eta 0:00:04
   ------------- -------------------------- 2.6/8.0 MB 1.7 MB/s eta 0:00:04
   ------------- -------------------------- 2.6/8.0 MB 1.7 MB/s eta 0:00:04
   -------------- ------------------------- 2.9/8.0 MB 1.6 MB/s eta 0:00:04
   ----------------- ---------------------- 3.4/8.0 MB 1.5 MB/s eta 0:00:04
   ------------------ --------------------- 3.7/8.0 MB 1.5 MB/s eta 0:00:03
   -------------------- ------------------- 4.2/8.0 MB 1.6 MB/s eta 0:00:03
   ------------------------ --------------- 5.0/8.0 MB 1.8 MB/s eta 0:00:02
   -------------------------- ------------- 5.2/8.0 MB 1.8 MB/s eta 0:00:02
   --------------------------- ------------ 5.5/8.0 MB 1.7 MB/s eta 0:00:02
   ---------------------------- ----------- 5.8/8.0 MB 1.7 MB/s eta 0:00:02
   ------------------------------ --------- 6.0/8.0 MB 1.7 MB/s eta 0:00:02
   ------------------------------- -------- 6.3/8.0 MB 1.6 MB/s eta 0:00:02
   ---------------------------------- ----- 6.8/8.0 MB 1.7 MB/s eta 0:00:01
   ----------------------------------- ---- 7.1/8.0 MB 1.7 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.0 MB 1.7 MB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 1.6 MB/s  0:00:04
Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.61.1-cp313-cp313-win_amd64.whl (2.3 MB)
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached kiwisolver-1.4.9-cp313-cp313-win_amd64.whl (73 kB)
Using cached pillow-12.0.0-cp313-cp313-win_amd64.whl (7.0 MB)
Using cached pyparsing-3.2.5-py3-none-any.whl (113 kB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached scipy-1.16.3-cp313-cp313-win_amd64.whl (38.5 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: pytz, tzdata, threadpoolctl, pyparsing, pillow, numpy, kiwisolver, joblib, fonttools, cycler, scipy, pandas, contourpy, scikit-learn, matplotlib, seaborn

   ----------------------------------------  0/16 [pytz]
   ----------------------------------------  0/16 [pytz]
   ----------------------------------------  0/16 [pytz]
   ----------------------------------------  0/16 [pytz]
   -- -------------------------------------  1/16 [tzdata]
   -- -------------------------------------  1/16 [tzdata]
   -- -------------------------------------  1/16 [tzdata]
   -- -------------------------------------  1/16 [tzdata]
   -- -------------------------------------  1/16 [tzdata]
   ----- ----------------------------------  2/16 [threadpoolctl]
   ------- --------------------------------  3/16 [pyparsing]
   ------- --------------------------------  3/16 [pyparsing]
   ---------- -----------------------------  4/16 [pillow]
   ---------- -----------------------------  4/16 [pillow]
   ---------- -----------------------------  4/16 [pillow]
   ---------- -----------------------------  4/16 [pillow]
   ---------- -----------------------------  4/16 [pillow]
   ---------- -----------------------------  4/16 [pillow]
   ---------- -----------------------------  4/16 [pillow]
   ---------- -----------------------------  4/16 [pillow]
   ---------- -----------------------------  4/16 [pillow]
   ---------- -----------------------------  4/16 [pillow]
   ---------- -----------------------------  4/16 [pillow]
   ---------- -----------------------------  4/16 [pillow]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   ------------ ---------------------------  5/16 [numpy]
   --------------- ------------------------  6/16 [kiwisolver]
   ----------------- ----------------------  7/16 [joblib]
   ----------------- ----------------------  7/16 [joblib]
   ----------------- ----------------------  7/16 [joblib]
   ----------------- ----------------------  7/16 [joblib]
   ----------------- ----------------------  7/16 [joblib]
   ----------------- ----------------------  7/16 [joblib]
   ----------------- ----------------------  7/16 [joblib]
   ----------------- ----------------------  7/16 [joblib]
   ----------------- ----------------------  7/16 [joblib]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   ---------------------- -----------------  9/16 [cycler]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [8]:
# Logistic Regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import cross_val_score

X = df.drop(["Species","Id"], axis=1)
y = df["Species"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:


model = LogisticRegression(C=0.5, max_iter=1000)  # smaller C = stronger regularization
model.fit(X_train, y_train)


y_pred = model.predict(X_test)

In [11]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

scores = cross_val_score(model, X, y, cv=5, scoring="accuracy")
print("Cross-validation scores:", scores)
print("Mean accuracy:", scores.mean())

Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Cross-validation scores: [0.96666667 0.96666667 0.93333333 0.96666667 1.        ]
Mean accuracy: 0.9666666666666668

In [17]:
# Take predictions for first 1 sample
data=[[6.3, 2.5, 5.0, 1.9]]
prediction = model.predict(data)
print("Prediction for data ",prediction)

species=le.inverse_transform(prediction)
print("Predicted species:", species)

Prediction for data  [2]
Predicted species: ['Iris-virginica']

c:\Users\786\Desktop\Sessions\MachineLearning---DeepLearning\02-Logistic-Regression\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

#### It is not overfitting, data is very simple